# Generated by Django 5.0.3 on 2024-03-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0008_user_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
